services:
  resume:
    build:
      context: .
      args:
        NUXT_PUBLIC_EMAILJS_SERVICE_ID: ${NUXT_PUBLIC_EMAILJS_SERVICE_ID:-}
        NUXT_PUBLIC_EMAILJS_TEMPLATE_ID: ${NUXT_PUBLIC_EMAILJS_TEMPLATE_ID:-}
        NUXT_PUBLIC_EMAILJS_PUBLIC_KEY: ${NUXT_PUBLIC_EMAILJS_PUBLIC_KEY:-}
    ports:
      - "8080:80"
    volumes:
      - ./public/cv-data-en.json:/usr/share/nginx/html/cv-data-en.json:ro
      - ./public/cv-data-fr.json:/usr/share/nginx/html/cv-data-fr.json:ro
      - ./public/cv-data-jp.json:/usr/share/nginx/html/cv-data-jp.json:ro
      - ./public/CV_Ghassen_Bargougui.pdf:/usr/share/nginx/html/CV_Ghassen_Bargougui.pdf:ro
