services:
  resume:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./public/cv-data-en.json:/usr/share/nginx/html/cv-data-en.json:ro
      - ./public/cv-data-fr.json:/usr/share/nginx/html/cv-data-fr.json:ro
      - ./public/cv-data-jp.json:/usr/share/nginx/html/cv-data-jp.json:ro
      - ./public/CV_Ghassen_Bargougui.pdf:/usr/share/nginx/html/CV_Ghassen_Bargougui.pdf:ro
      - ./public/CV_Ghassen_Bargougui-en.pdf:/usr/share/nginx/html/CV_Ghassen_Bargougui-en.pdf:ro
      - ./public/CV_Ghassen_Bargougui-fr.pdf:/usr/share/nginx/html/CV_Ghassen_Bargougui-fr.pdf:ro
      - ./public/CV_Ghassen_Bargougui-jp.pdf:/usr/share/nginx/html/CV_Ghassen_Bargougui-jp.pdf:ro
