apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume
spec:
  template:
    spec:
      containers:
        - name: resume
          image: ghassen-resume:latest
          volumeMounts:
            - name: cv-data
              mountPath: /usr/share/nginx/html/cv-data-en.json
              subPath: cv-data-en.json
              readOnly: true
            - name: cv-data
              mountPath: /usr/share/nginx/html/cv-data-fr.json
              subPath: cv-data-fr.json
              readOnly: true
            - name: cv-data
              mountPath: /usr/share/nginx/html/cv-data-jp.json
              subPath: cv-data-jp.json
              readOnly: true
            - name: cv-pdf
              mountPath: /usr/share/nginx/html/CV_Ghassen_Bargougui.pdf
              subPath: CV_Ghassen_Bargougui.pdf
              readOnly: true
      volumes:
        - name: cv-data
          configMap:
            name: resume-cv-data
        - name: cv-pdf
          configMap:
            name: resume-cv-pdf
